/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AgeRange = { '_45to54' : null } |
  { '_75plus' : null } |
  { '_25to34' : null } |
  { '_55to64' : null } |
  { '_18to24' : null } |
  { '_35to44' : null } |
  { '_65to74' : null };
export interface HealthLogEntry {
  'mood' : number,
  'notes' : string,
  'timestamp' : Time,
  'sleepHours' : number,
}
export type Time = bigint;
export interface UserProfile {
  'ageRange' : AgeRange,
  'name' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
  'healthGoals' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createHealthLogEntry' : ActorMethod<[number, number, string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHealthLogEntries' : ActorMethod<[], Array<HealthLogEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[string, AgeRange, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];