/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const FocusSession = IDL.Record({
  'sessionDate' : Time,
  'durationMinutes' : IDL.Nat,
});
export const Level = IDL.Variant({
  'beginner' : IDL.Null,
  'focusedMind' : IDL.Null,
  'consistent' : IDL.Null,
  'digitalMaster' : IDL.Null,
});
export const Challenge = IDL.Record({
  'id' : IDL.Nat,
  'endDate' : Time,
  'name' : IDL.Text,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
  'progress' : IDL.Nat,
  'startDate' : Time,
});
export const DigitalDetoxUser = IDL.Record({
  'streak' : IDL.Nat,
  'focusSessions' : IDL.Vec(FocusSession),
  'name' : IDL.Text,
  'createdAt' : Time,
  'callerUid' : IDL.Principal,
  'email' : IDL.Text,
  'level' : Level,
  'dailyLimit' : IDL.Nat,
  'currentScreenTime' : IDL.Nat,
  'totalPoints' : IDL.Nat,
  'challenges' : IDL.Vec(Challenge),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPoints' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChallenge' : IDL.Func([IDL.Text, IDL.Text, Time, Time], [], []),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, DigitalDetoxUser))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(DigitalDetoxUser)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChallengeProgress' : IDL.Func([], [IDL.Vec(Challenge)], ['query']),
  'getFocusSessions' : IDL.Func([], [IDL.Vec(FocusSession)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(DigitalDetoxUser)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([DigitalDetoxUser], [], []),
  'saveFocusSession' : IDL.Func([IDL.Nat], [], []),
  'updateChallengeProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const FocusSession = IDL.Record({
    'sessionDate' : Time,
    'durationMinutes' : IDL.Nat,
  });
  const Level = IDL.Variant({
    'beginner' : IDL.Null,
    'focusedMind' : IDL.Null,
    'consistent' : IDL.Null,
    'digitalMaster' : IDL.Null,
  });
  const Challenge = IDL.Record({
    'id' : IDL.Nat,
    'endDate' : Time,
    'name' : IDL.Text,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
    'progress' : IDL.Nat,
    'startDate' : Time,
  });
  const DigitalDetoxUser = IDL.Record({
    'streak' : IDL.Nat,
    'focusSessions' : IDL.Vec(FocusSession),
    'name' : IDL.Text,
    'createdAt' : Time,
    'callerUid' : IDL.Principal,
    'email' : IDL.Text,
    'level' : Level,
    'dailyLimit' : IDL.Nat,
    'currentScreenTime' : IDL.Nat,
    'totalPoints' : IDL.Nat,
    'challenges' : IDL.Vec(Challenge),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPoints' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChallenge' : IDL.Func([IDL.Text, IDL.Text, Time, Time], [], []),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, DigitalDetoxUser))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(DigitalDetoxUser)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChallengeProgress' : IDL.Func([], [IDL.Vec(Challenge)], ['query']),
    'getFocusSessions' : IDL.Func([], [IDL.Vec(FocusSession)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(DigitalDetoxUser)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([DigitalDetoxUser], [], []),
    'saveFocusSession' : IDL.Func([IDL.Nat], [], []),
    'updateChallengeProgress' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };