/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AgeRange = IDL.Variant({
  '_45to54' : IDL.Null,
  '_75plus' : IDL.Null,
  '_25to34' : IDL.Null,
  '_55to64' : IDL.Null,
  '_18to24' : IDL.Null,
  '_35to44' : IDL.Null,
  '_65to74' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'ageRange' : AgeRange,
  'name' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
  'healthGoals' : IDL.Text,
});
export const HealthLogEntry = IDL.Record({
  'mood' : IDL.Nat8,
  'notes' : IDL.Text,
  'timestamp' : Time,
  'sleepHours' : IDL.Nat8,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createHealthLogEntry' : IDL.Func([IDL.Nat8, IDL.Nat8, IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHealthLogEntries' : IDL.Func([], [IDL.Vec(HealthLogEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, AgeRange, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AgeRange = IDL.Variant({
    '_45to54' : IDL.Null,
    '_75plus' : IDL.Null,
    '_25to34' : IDL.Null,
    '_55to64' : IDL.Null,
    '_18to24' : IDL.Null,
    '_35to44' : IDL.Null,
    '_65to74' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'ageRange' : AgeRange,
    'name' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
    'healthGoals' : IDL.Text,
  });
  const HealthLogEntry = IDL.Record({
    'mood' : IDL.Nat8,
    'notes' : IDL.Text,
    'timestamp' : Time,
    'sleepHours' : IDL.Nat8,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createHealthLogEntry' : IDL.Func([IDL.Nat8, IDL.Nat8, IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHealthLogEntries' : IDL.Func([], [IDL.Vec(HealthLogEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, AgeRange, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };